### ISSUE TITLE
视频高度问题

### ISSUE THREAD

**Issue by GuixiangCao** [codeWorm2015/videoPlayer#3]
我设置了视频高度 在加载的时候视频高度是我设置的高度，然而加载完成 在播放的时候就会变高，请问这个bug 怎么解决。。。

**Comment by GuixiangCao** [comment]
解决了  哈哈

**Comment by RayLiu2015** [comment]
because before player initialed the view has a default height

**Comment by RayLiu2015** [comment]
because before player initialed the view has a default height
