### ISSUE TITLE
请问你的后台播放视频时怎么实现的。。。

### ISSUE THREAD

**Issue by guolidemayi** [codeWorm2015/videoPlayer#5]
我上网查的貌似需要音频视频切换，很麻烦，你写的例子就不用，指导一下，非常感谢

**Comment by RayLiu2015** [comment]
后台播放在 AVPlayer实现的播放器 实现起来很简单:

**第一步.** 首先确保工程配置处 Capabilities 选项下 Background Modes 打开, 并且选择 (Audio, AirPlay, and Picture in Picture) 那个选项, 配置这个是用来告诉系统, 这个APP要申请后台音频播放任务的; 

**第二步.** 首先你要知道AVPlayer其实是绘制在AVPlayerLayer上的, 系统要求进入后台后是不允许绘制的, 所以要在即将进入后台(appWillResignActive)时: 
`[(AVPlayerLayer *)self.avplayerView.layer setPlayer:nil];`
 在返回前台(appDidBecomeActive)后:
 `[(AVPlayerLayer *)self.avplayerView.layer setPlayer:self.avplayer];`
到此就可以实现后台播放了, 如果你想在程序使用过程中关闭后台播放模式, 及进入后台不播放声音, 那就见下一步;

**第三步.** 非后台播放模式下, 在即将进入后台和进入前台后, 使用以下方法:
`
    [self.avplayer pause];
`
`
    [self.avplayer play];
`
来控制暂停和播放;



如果你使用的是ffmpeg播放器, 和上述步骤同理, 只不过使用ffmpeg封装的播放器是使用openGL进行绘制的, 并且绘制部分也是由我们自己写的, 所以在即将进入后台时 关闭绘制, 返回前台 继续绘制 即可;
