### ISSUE TITLE
视频播放支持的格式

### ISSUE THREAD

**Issue by saberChen** [codeWorm2015/videoPlayer#7]
支持的格式有哪些的，因为在播放rmvb，avi等都提示不支持，不知道什么原因，还是哪里需要配置的？

**Comment by RayLiu2015** [comment]
这个播放器是基于AVPlayer封装的,  不是所有视频格式都能支持, 支持的常见视频格式有 mp4, mov, m3u8; 如果你想找支持全格式的视频播放器, 可以找基于 ffmpeg封装的播放器, 比如Blili做的这个, 就是比较不错的: 
https://github.com/Bilibili/ijkplayer
